<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPlaceOrder</name>
   <tag></tag>
   <elementGuidId>8b00f6e3-7efa-4923-b21d-e3f6e2b147c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;place_order&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;place_order&quot;]</value>
      <webElementGuid>5385c55b-3eb3-48a6-a3d0-d03e9c5ee3be</webElementGuid>
   </webElementProperties>
</WebElementEntity>
